# Generated by Django 4.2.7 on 2023-11-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('image', models.CharField(default='images/default.png', max_length=100)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
    ]
